package com.fourguard.wms.application.mapper;

import com.fourguard.wms.application.dto.request.CreateSupplierRequest;
import com.fourguard.wms.application.dto.request.SupplierAddressRequest;
import com.fourguard.wms.application.dto.request.SupplierCommercialTermsRequest;
import com.fourguard.wms.application.dto.request.SupplierContactRequest;
import com.fourguard.wms.application.dto.request.UpdateSupplierRequest;
import com.fourguard.wms.application.dto.response.*;
import com.fourguard.wms.infrastructure.persistence.entity.*;
import org.mapstruct.*;

import java.util.UUID;

/**
 * MapStruct mapper for Supplier domain.
 *
 * Key field translations (FE ↔ BE ↔ DB):
 * <ul>
 *   <li>DTO 'type'           ↔ SupplierEntity 'supplierTypeCode'</li>
 *   <li>DTO 'preferred'      ↔ SupplierEntity 'isPreferred'</li>
 *   <li>DTO 'warehouseId'    ↔ SupplierEntity.branch.id (branch_id in DB)</li>
 *   <li>DTO 'active'         ↔ SupplierEntity 'isActive'</li>
 *   <li>DTO 'deleted'        ↔ SupplierEntity 'isDeleted'</li>
 *   <li>CommercialTerms DTO 'currency' ↔ Entity 'currencyCode'</li>
 * </ul>
 */
@Mapper(componentModel = "spring")
public interface SupplierMapper {

    // =========================================================================
    // CREATE: Request → Entity
    // =========================================================================

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "organization", ignore = true)
    @Mapping(target = "client", ignore = true)
    @Mapping(target = "branch", ignore = true)
    @Mapping(target = "contact", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "commercialTerms", ignore = true)
    @Mapping(target = "code", ignore = true)                // Generated by service
    @Mapping(target = "status", ignore = true)               // Defaults to ACTIVE
    @Mapping(target = "scopeType", ignore = true)            // Handled in service with enum conversion
    @Mapping(target = "statusReason", ignore = true)
    @Mapping(target = "statusChangedAt", ignore = true)
    @Mapping(target = "statusChangedBy", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    @Mapping(target = "isDeleted", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "deletedBy", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(source = "type", target = "supplierTypeCode")
    @Mapping(source = "preferred", target = "isPreferred")
    SupplierEntity toEntity(CreateSupplierRequest request);

    // Contact sub-mapping
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    SupplierContactEntity toContactEntity(SupplierContactRequest request);

    // Address sub-mapping
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "country", source = "country", defaultValue = "México")
    SupplierAddressEntity toAddressEntity(SupplierAddressRequest request);

    // Commercial terms sub-mapping
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(source = "currency", target = "currencyCode")
    SupplierCommercialTermsEntity toCommercialTermsEntity(SupplierCommercialTermsRequest request);

    // =========================================================================
    // RESPONSE: SupplierEntity → SupplierResponse (full detail)
    // =========================================================================

    @Mapping(source = "organization.id", target = "organizationId")
    @Mapping(source = "supplierTypeCode", target = "type")
    @Mapping(source = "isPreferred", target = "preferred")
    @Mapping(source = "status", target = "status")
    @Mapping(source = "scopeType", target = "scopeType")
    @Mapping(source = "client.id", target = "clientId")
    @Mapping(source = "branch.id", target = "warehouseId")     // branch_id → warehouseId
    @Mapping(source = "isActive", target = "active")
    @Mapping(source = "isDeleted", target = "deleted")
    SupplierResponse toResponse(SupplierEntity entity);

    @Mapping(source = "fullName", target = "fullName")
    SupplierResponse.ContactResponse toContactResponse(SupplierContactEntity entity);

    SupplierResponse.AddressResponse toAddressResponse(SupplierAddressEntity entity);

    @Mapping(source = "currencyCode", target = "currency")     // currencyCode → currency
    SupplierResponse.CommercialTermsResponse toCommercialTermsResponse(SupplierCommercialTermsEntity entity);

    // =========================================================================
    // RESPONSE: SupplierEntity → SupplierSummaryResponse (list view)
    // =========================================================================

    @Mapping(source = "supplierTypeCode", target = "type")
    @Mapping(source = "isPreferred", target = "preferred")
    @Mapping(source = "status", target = "status")
    @Mapping(source = "scopeType", target = "scopeType")
    @Mapping(source = "client.id", target = "clientId")
    @Mapping(source = "branch.id", target = "warehouseId")
    @Mapping(source = "isActive", target = "active")
    SupplierSummaryResponse toSummaryResponse(SupplierEntity entity);

    @Mapping(source = "fullName", target = "fullName")
    @Mapping(source = "email", target = "email")
    @Mapping(source = "phone", target = "phone")
    SupplierSummaryResponse.ContactSummary toContactSummary(SupplierContactEntity entity);

    // =========================================================================
    // CATALOG RESPONSES
    // =========================================================================

    @Mapping(source = "sortOrder", target = "sortOrder")
    SupplierTypeResponse toTypeResponse(CatSupplierTypeEntity entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "organizationId", ignore = true)
    @Mapping(target = "isBase", ignore = true)
    @Mapping(target = "decimalPlaces", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(source = "label", target = "name")
    @Mapping(target = "status", expression = "java(entity.getActive() != null && entity.getActive() ? com.fourguard.wms.domain.enums.CurrencyStatus.ACTIVE : com.fourguard.wms.domain.enums.CurrencyStatus.INACTIVE)")
    CurrencyResponse toCurrencyResponse(CatCurrencyEntity entity);

    // =========================================================================
    // UPDATE: UpdateSupplierRequest → existing SupplierEntity (in-place merge)
    // =========================================================================

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "organization", ignore = true)
    @Mapping(target = "client", ignore = true)
    @Mapping(target = "branch", ignore = true)
    @Mapping(target = "contact", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "commercialTerms", ignore = true)
    @Mapping(target = "code", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "scopeType", ignore = true)
    @Mapping(target = "statusReason", ignore = true)
    @Mapping(target = "statusChangedAt", ignore = true)
    @Mapping(target = "statusChangedBy", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    @Mapping(target = "isDeleted", ignore = true)
    @Mapping(target = "deletedAt", ignore = true)
    @Mapping(target = "deletedBy", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "updatedBy", ignore = true)
    @Mapping(source = "type", target = "supplierTypeCode")
    @Mapping(source = "preferred", target = "isPreferred")
    void updateEntityFromDto(UpdateSupplierRequest request, @MappingTarget SupplierEntity entity);

    // Contact update (in-place)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateContactFromDto(SupplierContactRequest request, @MappingTarget SupplierContactEntity entity);

    // Address update (in-place)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateAddressFromDto(SupplierAddressRequest request, @MappingTarget SupplierAddressEntity entity);

    // Commercial terms update (in-place)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "supplier", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(source = "currency", target = "currencyCode")
    void updateCommercialTermsFromDto(SupplierCommercialTermsRequest request, @MappingTarget SupplierCommercialTermsEntity entity);
}
