package com.fourguard.wms.domain.enums;

public enum AlertEvent {
    WAIT_TIME_EXCEEDED,
    LOW_INVENTORY,
    LOT_EXPIRATION,
    UNAUTHORIZED_ACCESS,
    DEVICE_OFFLINE,
    INVENTORY_DISCREPANCY,
    ORDER_DELAYED,
    PENDING_ASN,
    HALTED_PICKING,
    USER_LOCKED,
    SYSTEM_ERROR,
    INTEGRATION_ERROR,
    SHIPMENT_DELAYED
}
